Repository kinyean/LivinDex, pull requests merged in 2025-05, with the labels that each got.

#76 Fix bug
  my-app/src/Components/Navbar.tsx
  my-app/src/Pages/Login.tsx
  my-app/src/Styles/App.css
  my-app/src/Styles/Content.css
  my-app/src/Styles/Filter.css
  my-app/src/Styles/Home.css
  my-app/src/Styles/Navbar.css
  my-app/src/Styles/Profile.css
  my-app/src/Styles/Slider.css
Labels: bug

#82 add upload file function
  my-app/src/Components/ContentTab.tsx
  my-app/src/index.tsx
Labels: priority.High

#83 implement forget password
  my-app/src/Pages/ForgotPassword.tsx
Labels: enhancement

#88 small fix
  my-app/src/Components/Comment/CommentTextBox.tsx
  my-app/src/Components/Comment/Comments.tsx
Labels: bug, priority.Low

#96 comment (front end) done
  my-app/src/Components/Comment/CommentDummyDB.tsx
  my-app/src/Components/Comment/CommentForm.tsx
  my-app/src/Components/Comment/CommentTextBox.tsx
  my-app/src/Components/Comment/Comments.tsx
Labels: priority.High

#101 Add Backend
  my-app/Backend/controllers/commentController.js
  my-app/Backend/firebase.js
  my-app/Backend/routes/commentRoutes.js
  my-app/Backend/server.js
  my-app/src/API/BaseAPI.ts
  my-app/src/API/README.md
  my-app/src/Components/Comment/CommentDummyDB.tsx
Labels: bug, priority.High

#122 Implement Backend
  my-app/Backend/controllers/userController.js
  my-app/Backend/routes/userRoutes.js
  my-app/Backend/routes/users.js
  my-app/Backend/server.js
  my-app/Frontend/src/App.tsx
  my-app/Frontend/src/Pages/Profile/EditProfile.tsx
  my-app/Frontend/src/Pages/Profile/GetProfile.tsx
  my-app/Frontend/src/Pages/Profile/Registration.tsx
Labels: priority.High

#124 Backend DB Done for Profile (Edit)
  my-app/Backend/controllers/userController.js
  my-app/Frontend/src/Pages/Profile/EditProfile.tsx
  my-app/Frontend/src/Pages/Profile/GetProfile.tsx
  my-app/Frontend/src/Pages/Profile/Registration.tsx
Labels: priority.High

#126 Disable Update Button
  my-app/Frontend/src/Pages/Profile/EditProfile.tsx
Labels: enhancement
